### ISSUE TITLE
The form input field's placeholder text is grainy and sharp. Home.vue & Food.vue

### ISSUE THREAD

**Issue by AHaibli** [Bramwell-Simpson/Calorie-Counter-Team-Project#5]

**Comment by AHaibli** [comment]
Commenting this out `/* filter: brightness(1.2) contrast(1.2); */` removes the issue.

**Comment by AAlarifi** [comment]
Removing this out /* filter: brightness(1.2) contrast(1.2); */ removes the issue.

**Comment by AHaibli** [comment]
Removing this out /* filter: brightness(1.2) contrast(1.2); */ removes the issue.
